# Generated by Django 4.0.5 on 2022-06-05 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Ovqat turi')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ovqat xili')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='api.category')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Ovqat nomi')),
                ('image', models.ImageField(upload_to='foods_image/', verbose_name='Rasmi')),
                ('sale_type', models.CharField(choices=[('qt', 'quantity'), ('wg', 'weight'), ('sv', 'serving')], max_length=50)),
                ('price', models.PositiveIntegerField(verbose_name='Narxi (so`mda)')),
                ('discount', models.PositiveIntegerField(blank=True, verbose_name='Chegirma %')),
                ('price_discounted', models.PositiveIntegerField(blank=True, verbose_name='Chegirmali narxi')),
                ('info', models.TextField(verbose_name='Malumoti')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='api.subcategory')),
            ],
        ),
    ]
