# Generated by Django 4.0.5 on 2022-06-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='discount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Chegirma %'),
        ),
        migrations.AlterField(
            model_name='food',
            name='price_discounted',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Chegirmali narxi'),
        ),
    ]
