# Generated by Django 4.0.5 on 2022-06-05 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, verbose_name='Tug`ulgan sanasi')),
                ('location', models.CharField(blank=True, max_length=400, verbose_name='Lakatsiyasi')),
                ('gender', models.CharField(blank=True, max_length=6, verbose_name='Jinsi male/female')),
                ('avatar', models.ImageField(blank=True, upload_to='avatars/', verbose_name='Rasmi')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Soni')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='Og`irligi')),
                ('serving', models.FloatField(blank=True, null=True, verbose_name='Porsiya')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_carts', to='api.food')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
